### ISSUE TITLE
Support for grpc streaming

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#133]
Should we add support for grpc streaming? 

If we did, we could have it as a Gunk annotation `+gunk.GRPCStream` or something, or apart of the syntax `Echo(chan Message) chan Message`?

Not entirely sure how protoc generates the `FileDescriptorProto` with `stream` set for a service, need to investigate further.

**Comment by mvdan** [comment]
Agreed that we should support streaming. `chan T` seems fine, as long as we don't allow combinations like `chan *T` or `<-chan T`.

Another option, to further clarify the directions of the channel, could be:

```
Endpoint(<-chan InputType) <-chan OutputType
```

But I think it's clear enough without being explicit about the channel directions.

/cc @kenshaw and also @Kunde21, since he has some experience with grpc streams.

**Comment by kenshaw** [comment]
Yes, the original plan for syntax has always been to use channels.

**Comment by kenshaw** [comment]
To clarify: use the same type definitions as are generated in the Go files generated by protoc.

**Comment by vishen** [comment]
The streaming option can be set on the `MethodDescriptorProto`, there is an option for [client_streaming](https://github.com/protocolbuffers/protobuf/blob/de9e1a04a68af0c8c5f49121ebd7dd1a2fed37af/src/google/protobuf/descriptor.proto#L279) and one for [server_streaming](https://github.com/protocolbuffers/protobuf/blob/de9e1a04a68af0c8c5f49121ebd7dd1a2fed37af/src/google/protobuf/descriptor.proto#L281).
