### ISSUE TITLE
main: rename "format" to "fmt"

### ISSUE THREAD

**Issue by mvdan** [gunk/gunk#178]
The original issue, #37, called this command `fmt`. Go has `go fmt`. I honestly can't remember why I went with `gunk format`.

I guess my reasoning was that we had `gunk generate` and not `gunk gen`, so we should use non-abbreviated names for all commands. Then again, `gunk fmt` will be run often, and consistency with the Go commands would be good.

Moreover, keeping master as it is now would mean that #124 would have to be called something like "document", which just seems wrong.

One question that does come to me is why Go went with `go generate` instead of something shorter like `go gen`.

@vishen @kenshaw thoughts? I think we should default to copying Go here. I can send a PR in the morning.

**Comment by vishen** [comment]
You are correct, I believe that is why we went with `gunk format`; because we already had `gunk generate` and not `gunk gen`.

I think it would actually be `gunk documentation`, but I agree that that is too long and verbose. 

`gunk doc` and `gunk fmt` are fairly unambiguous to me (probably because I am used to the `go` tools), so they kind of make sense to have as the shortened version. But having `gunk con` (or `gunk conv`) and `gunk gen` aren't immediately obvious to me for what they would do.

We could also have both short, and long names for each command; `doc and documentation`, `conv and convert`, `gen and generate`, `fmt and format` and `dump`?

It makes sense to me to keep the ambiguous names as the longer names, but I do prefer the shorter names for `doc` and `fmt` which is much easier to type.

**Comment by kenshaw** [comment]
Let's stay with `format` please.
