### ISSUE TITLE
loader: support loading proto files as part of Gunk packages

### ISSUE THREAD

**Issue by mvdan** [gunk/gunk#194]
We want to support easier backwards compatibility with projects using `.proto` files. However, we don't want to allow Gunk files "importing" lone proto files, as that would be complex and go against the Gunk design of working with packages.

The cleanest solution is to allow loading `.proto` files within Gunk packages, as if they had been converted via `gunk convert`. That way, a project can mix Gunk and proto while they're trying out Gunk, or old proto codebases can be made importable via Gunk by just adding a single Go or Gunk file.

I have an idea on how to implement this; shouldn't be too hard. I might need to refactor the `convert` package a bit, depending on what kind of API I end up needing. Most notably, we need to be careful because we can't end up with cyclic package imports.

/cc @vishen @kenshaw

**Comment by vishen** [comment]
Currently `convert` will convert the declarations and fields to idiomatic Go naming style (`camelCase`), and this might be a bit confusing for the user when trying to use these fields in the `.gunk` file.

For example;

```
# example.proto

message msg {
    string message = 1;
    string error_code = 2;
}
```

would convert to;

```
# example.gunk

type Msg struct {
    Message string
    ErrorCode string
}
```

so, the user will need to use `Msg.Message` rather than `msg.message` if trying to access that field from another gunk file. I am not sure if we want to keep it this way for converting a proto file for loading, but I think we likely would? I guess we would just need some documentation saying that fields and declarations are converted to `camelCase`.

**Comment by mvdan** [comment]
I think we should change the names. The obvious disadvantage is that it could confuse some users who aren't familiar with Gunk. However, I see multiple advantages:

* Idiomatic Gunk/Go code
* Messages and services get exported automatically, due to the capitalization; cross-package imports of protos are possible
* One can write `new.gunk` which uses `old.proto`, and later use `gunk convert old.proto` which would keep everything working with near-zero changes to `new.gunk`

But like you say, we should document this well.
