### ISSUE TITLE
Is it possible to hack around the need for a 'doc.go'

### ISSUE THREAD

**Issue by vishen** [gunk/gunk#89]
In each gunk package, we obviously need a 'doc.go' or similar for the Go loader to work (I think). It would be useful if we could avoid the need for having a `doc.go` or similar on disk. Not sure if this is possible though?

**Comment by mvdan** [comment]
I've dealt with Go package loading and static analysis quite a bit, so I'll take a look. I knew this was a hack from day one, but I just wanted Gunk to work with modules one way or another.

I have a couple of potential ideas in mind, which I'll investigate in the next week or two. It can certainly be done - the question is whether it can be done in a reasonable amount of code and still be decently precise.

**Comment by kenshaw** [comment]
Are we generating a temporary working directory, for creating `proto` files? If so, the easiest hack would be to see if there are any readable `.go` files, and if there aren't, just generate one with a name like `_gunk_<random>.go` in the directory with a package name, and erase it after running.

**Comment by mvdan** [comment]
There's no temporary directory involved, as all generation can happen via proto files in protobuf format passed via stdin/stdout.

Anyway, that wouldn't work in the general sense, because the need for the `doc.go` files is so that we can do `gunk generate ./...` and find the Gunk packages. The `...` patterns skip directories with zero Go files, as these are not Go packages.

The simplest short-term solution that comes to mind is to say that we require Go modules and `go list` to work, in which case we can hard-code the use of commands like `go list -e -f {{.Dir}} ./...`. That way, we can find the directories having some Gunk files and zero Go files, and adapt them so that the actual `packages.Load` doesn't skip the packages or error on them.

The second, and best solution long-term is something I've been talking about with the Go tooling team at Google. They already have some ways to modify a package's syntax tree before loading, e.g. ParseFiel in https://godoc.org/golang.org/x/tools/go/packages#Config. This is so that IDEs can load a package with a modified file in memory, for example.

That doesn't support adding **new** files or packages, which is what they're currently considering. If they added that functionality, we could simply use it to give the loader the Gunk files as if they were Go files.

It may take them weeks or months to come up with a design and implement it though, so I think I'll go with a short-term hack like the first option.
